version: 2
updates:
  # Enable version updates for Python/Pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # to pip against the `main` branch
    target-branch: "main"
    # Labels on pull requests for version updates only
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Specify additional updates to security updates
    open-pull-requests-limit: 10

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # to npm against the `main` branch
    target-branch: "main"
    # Labels on pull requests for version updates only
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Specify additional updates to security updates
    open-pull-requests-limit: 10 