services:
  # Backend API Service
  - type: web
    name: grant-dashboard-api
    env: python
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///grants.db
      - key: CORS_ORIGINS
        value: https://grant-dashboard-frontend.onrender.com
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: static
    name: grant-dashboard-frontend
    buildCommand: |
      cd frontend
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://grant-dashboard-api.onrender.com
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 