services:
  # Backend API Service
  - type: web
    name: grant-application-dashboard-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: grant-application-dashboard-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: grant-application-dashboard-redis
          property: connectionString
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://grant-application-dashboard-frontend.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: grant-application-dashboard-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://grant-application-dashboard-api.onrender.com
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis Service
  - type: redis
    name: grant-application-dashboard-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: grant-application-dashboard-db
    databaseName: grantdb
    user: grantuser
    plan: free 